// part2/staff/ids.js
const STAFF_IDS = Object.freeze({
  CMD: "staff",

  // subcommands
  SUB_PANEL: "panel",
  SUB_CONFIG: "config",
  SUB_LOGS: "logs",
  SUB_DIAG: "diag",
  SUB_MAINT: "maintenance",

  // panels (buttons)
  BTN_PANEL_HOME: "P2_STAFF_HOME",
  BTN_PANEL_MOD: "P2_STAFF_MOD",
  BTN_PANEL_ANN: "P2_STAFF_ANN",
  BTN_PANEL_AUTOROLE: "P2_STAFF_AUTOROLE",
  BTN_PANEL_CONFIG: "P2_STAFF_CONFIG",

  // moderation actions
  BTN_MOD_WARN: "P2_STAFF_MOD_WARN",
  BTN_MOD_TIMEOUT: "P2_STAFF_MOD_TIMEOUT",
  BTN_MOD_KICK: "P2_STAFF_MOD_KICK",
  BTN_MOD_BAN: "P2_STAFF_MOD_BAN",
  BTN_MOD_PURGE: "P2_STAFF_MOD_PURGE",

  // announcement actions
  SELECT_ANN_TEMPLATE: "P2_STAFF_ANN_TEMPLATE",
  BTN_ANN_EDIT: "P2_STAFF_ANN_EDIT",
  BTN_ANN_PUBLISH: "P2_STAFF_ANN_PUBLISH",
  BTN_ANN_PUBLISH_SILENT: "P2_STAFF_ANN_PUBLISH_SILENT",
  BTN_ANN_PUBLISH_MENTION: "P2_STAFF_ANN_PUBLISH_MENTION",
  BTN_ANN_CANCEL: "P2_STAFF_ANN_CANCEL",

  // logs
  SELECT_LOG_FILTER: "P2_STAFF_LOG_FILTER",
  BTN_LOG_REFRESH: "P2_STAFF_LOG_REFRESH",

  // config
  BTN_CFG_EDIT: "P2_STAFF_CFG_EDIT",
  BTN_CFG_TOGGLE_MAINT: "P2_STAFF_CFG_TOGGLE_MAINT",

  // modals
  MODAL_CFG: "P2_STAFF_MODAL_CFG",
  MODAL_WARN: "P2_STAFF_MODAL_WARN",
  MODAL_TIMEOUT: "P2_STAFF_MODAL_TIMEOUT",
  MODAL_KICK: "P2_STAFF_MODAL_KICK",
  MODAL_BAN: "P2_STAFF_MODAL_BAN",
  MODAL_PURGE: "P2_STAFF_MODAL_PURGE",
  MODAL_ANN_EDIT: "P2_STAFF_MODAL_ANN_EDIT",
});

module.exports = { STAFF_IDS };
