// part2/staff/ids.js
// IDs du panel staff (boutons, selects, modals)

const STAFF_IDS = {
  BTN_MOD: 'LGW_STAFF:BTN_MOD',
  BTN_PANELS: 'LGW_STAFF:BTN_PANELS',
  BTN_AUTORESP: 'LGW_STAFF:BTN_AUTORESP',
  BTN_CONFIG: 'LGW_STAFF:BTN_CONFIG',
  BTN_CHAN_TOOLS: 'LGW_STAFF:BTN_CHAN_TOOLS',
  BTN_HELP: 'LGW_STAFF:BTN_HELP',
  BTN_CLOSE: 'LGW_STAFF:BTN_CLOSE',

  BTN_PUB_TICKETS: 'LGW_STAFF:PUB_TICKETS',
  BTN_PUB_APPS: 'LGW_STAFF:PUB_APPS',
  BTN_PUB_SUGG: 'LGW_STAFF:PUB_SUGG',

  CFG_SET_LOGS: 'LGW_STAFF:CFG_SET_LOGS',
  CFG_SET_TICKET_CAT: 'LGW_STAFF:CFG_SET_TICKET_CAT',
  CFG_SET_TICKET_LOGS: 'LGW_STAFF:CFG_SET_TICKET_LOGS',
  CFG_SET_APPS_REVIEW: 'LGW_STAFF:CFG_SET_APPS_REVIEW',
  CFG_SET_SUGG_CH: 'LGW_STAFF:CFG_SET_SUGG_CH',
  CFG_SET_WELCOME: 'LGW_STAFF:CFG_SET_WELCOME',
  CFG_SET_LEAVE: 'LGW_STAFF:CFG_SET_LEAVE',
  CFG_SET_STAFF_ROLES: 'LGW_STAFF:CFG_SET_STAFF_ROLES',
  CFG_SET_APP_ROLE: 'LGW_STAFF:CFG_SET_APP_ROLE',
  CFG_EDIT_WELCOME_TEXT: 'LGW_STAFF:CFG_EDIT_WELCOME_TEXT',
  CFG_EDIT_LEAVE_TEXT: 'LGW_STAFF:CFG_EDIT_LEAVE_TEXT',

  CH_LOCK: 'LGW_STAFF:CH_LOCK',
  CH_UNLOCK: 'LGW_STAFF:CH_UNLOCK',
  CH_SLOWMODE: 'LGW_STAFF:CH_SLOWMODE',

  MOD_WARN: 'LGW_STAFF:MOD_WARN',
  MOD_TIMEOUT: 'LGW_STAFF:MOD_TIMEOUT',
  MOD_UNTIMEOUT: 'LGW_STAFF:MOD_UNTIMEOUT',
  MOD_PURGE: 'LGW_STAFF:MOD_PURGE',

  AR_LIST: 'LGW_STAFF:AR_LIST',
  AR_ADD: 'LGW_STAFF:AR_ADD',
  AR_REMOVE: 'LGW_STAFF:AR_REMOVE',

  SEL_CHANNEL: 'LGW_STAFF:SEL_CHANNEL',
  SEL_CATEGORY: 'LGW_STAFF:SEL_CATEGORY',
  SEL_ROLE: 'LGW_STAFF:SEL_ROLE',

  MODAL_WELCOME: 'LGW_STAFF:MODAL_WELCOME',
  MODAL_LEAVE: 'LGW_STAFF:MODAL_LEAVE',
  MODAL_WARN: 'LGW_STAFF:MODAL_WARN',
  MODAL_TIMEOUT: 'LGW_STAFF:MODAL_TIMEOUT',
  MODAL_PURGE: 'LGW_STAFF:MODAL_PURGE',

  MODAL_AR_ADD: 'LGW_STAFF:MODAL_AR_ADD',
  MODAL_AR_REMOVE: 'LGW_STAFF:MODAL_AR_REMOVE',
  MODAL_SLOWMODE: 'LGW_STAFF:MODAL_SLOWMODE',
};

module.exports = { STAFF_IDS };
