// part2/autorole/ids.js
const AUTOROLE_IDS = {
  // wizard selects
  WIZ_ROLE_SELECT: "AR_WIZ_ROLE_SELECT",
  WIZ_CHANNEL_SELECT: "AR_WIZ_CHANNEL_SELECT",

  // wizard buttons
  WIZ_TOGGLE_MODE: "AR_WIZ_TOGGLE_MODE",
  WIZ_TOGGLE_MULTI: "AR_WIZ_TOGGLE_MULTI",
  WIZ_TOGGLE_REPLACEMENT: "AR_WIZ_TOGGLE_REPLACEMENT",
  WIZ_TOGGLE_TEMP: "AR_WIZ_TOGGLE_TEMP",
  WIZ_EDIT_STYLE: "AR_WIZ_EDIT_STYLE",
  WIZ_EDIT_DURATION: "AR_WIZ_EDIT_DURATION",
  WIZ_PUBLISH: "AR_WIZ_PUBLISH",
  WIZ_CANCEL: "AR_WIZ_CANCEL",

  // modals
  MODAL_STYLE: "AR_MODAL_STYLE",
  MODAL_DURATION: "AR_MODAL_DURATION",

  // public menu
  PUBLIC_MENU: "AR_PUBLIC_MENU",
};

module.exports = { AUTOROLE_IDS };
