// part2/modules/ids.js
// IDs utilisés par les modules (tickets, applications, suggestions)
// ✅ Exporte aussi des alias legacy pour éviter les bugs: TICKET_IDS / APP_IDS / SUGG_IDS

// --- Noms “officiels” ---
const TICKETS_IDS = {
  PANEL_OPEN: 'LGW_TICKETS:OPEN',
  TICKET_CLOSE: 'LGW_TICKETS:CLOSE',
};

const APPLICATION_IDS = {
  PANEL_OPEN: 'LGW_APPS:OPEN',
  MODAL: 'LGW_APPS:MODAL',
  BTN_APPROVE_PREFIX: 'LGW_APPS:APPROVE:',
  BTN_REJECT_PREFIX: 'LGW_APPS:REJECT:',
};

const SUGGEST_IDS = {
  PANEL_OPEN: 'LGW_SUGG:OPEN',
  MODAL: 'LGW_SUGG:MODAL',
};

// --- Aliases legacy ---
// Certains fichiers plus anciens utilisent OPEN/CLOSE + APPROVE/REJECT (sans "_PREFIX").
const TICKET_IDS = {
  OPEN: TICKETS_IDS.PANEL_OPEN,
  CLOSE: TICKETS_IDS.TICKET_CLOSE,
  PANEL_OPEN: TICKETS_IDS.PANEL_OPEN,
  TICKET_CLOSE: TICKETS_IDS.TICKET_CLOSE,
};

const APP_IDS = {
  OPEN: APPLICATION_IDS.PANEL_OPEN,
  MODAL: APPLICATION_IDS.MODAL,
  APPROVE: APPLICATION_IDS.BTN_APPROVE_PREFIX,
  REJECT: APPLICATION_IDS.BTN_REJECT_PREFIX,
  PANEL_OPEN: APPLICATION_IDS.PANEL_OPEN,
  BTN_APPROVE_PREFIX: APPLICATION_IDS.BTN_APPROVE_PREFIX,
  BTN_REJECT_PREFIX: APPLICATION_IDS.BTN_REJECT_PREFIX,
};

const SUGG_IDS = {
  OPEN: SUGGEST_IDS.PANEL_OPEN,
  MODAL: SUGGEST_IDS.MODAL,
  PANEL_OPEN: SUGGEST_IDS.PANEL_OPEN,
};

module.exports = {
  // Noms “officiels”
  TICKETS_IDS,
  APPLICATION_IDS,
  SUGGEST_IDS,

  // Aliases compat
  TICKET_IDS,
  APP_IDS,
  SUGG_IDS,
};
